insert into User_Details values ('9385', 'lrbbmqbh', 'darz', '7513928', 'kk', crypt('hi', gen_salt('bf')));
insert into User_Details values ('2569', 'qscdxrjmowf', 'xsjybldbe', '6898539', 'arcbynecdyggxxpklore', crypt('lnm', gen_salt('bf')));
insert into User_Details values ('3897', 'pqfw', 'hopkmc', '695790', 'hnwnku', crypt('whsqmg', gen_salt('bf')));
insert into User_Details values ('7541', 'uqcljji', 'swmdkqtbx', '4228446', 'mvtrrbljptnsnfwzqfjma', crypt('adrrwsofs', gen_salt('bf')));
insert into User_Details values ('8151', 'nuvqhffb', 'aqxwpqcace', '8936989', 'hzvfrkmlnozjkpqpxr', crypt('xkitz', gen_salt('bf')));
insert into User_Details values ('5930', 'acbhhkicqco', 'ndtomfgdwd', '6689774', 'cgpxiqv', crypt('uytd', gen_salt('bf')));
insert into User_Details values ('9357', 'gdewht', 'ciohordt', '6473732', 'vwcsgspqoqmsboaguwnn', crypt('qxnzlgdg', gen_salt('bf')));
insert into User_Details values ('8662', 'btrwb', 'nsade', '7116468', 'uumoqc', crypt('rubet', gen_salt('bf')));
insert into User_Details values ('9414', 'yxhoachwdv', 'xxrd', '7517723', 'xlmndq', crypt('ukwagmlej', gen_salt('bf')));
insert into User_Details values ('5632', 'kwcibx', 'bume', '6340715', 'eyatdrmydiajxloghiqf', crypt('zhlvih', gen_salt('bf')));
insert into User_Details values ('1963', 'uvsuyo', 'payuly', '7949910', 'muotehzriicfskpggkbb', crypt('pzzrzucx', gen_salt('bf')));
insert into User_Details values ('1154', 'ludfykgr', 'ow', '8388029', 'iooobppleqlw', crypt('hap', gen_salt('bf')));
insert into User_Details values ('5153', 'adqhdcn', 'wdtxjbmyppp', '5495369', 'uxnspusgdh', crypt('ixqm', gen_salt('bf')));
insert into User_Details values ('9119', 'jxjcv', 'djsuyiby', '6673170', 'mwsiqyo', crypt('gyxymz', gen_salt('bf')));
insert into User_Details values ('6972', 'ypz', 'jegebeocf', '1909612', 'tsxdixtigsi', crypt('ehkchz', gen_salt('bf')));
insert into User_Details values ('7207', 'lilrjqfnxzt', 'rsvbspkyhs', '4633076', 'bppkqtpddbuotbb', crypt('cwivrfxj', gen_salt('bf')));
insert into User_Details values ('8576', 'jdd', 'tge', '3614032', 'vdgaijvwcyaubwewpjvy', crypt('eh', gen_salt('bf')));
insert into User_Details values ('9209', 'xepbpiwuqzd', 'ubdubzvafsp', '9544920', 'qwuzifw', crypt('vyddwyvv', gen_salt('bf')));
insert into User_Details values ('8379', 'rczm', 'yjgf', '7871139', 'vtnunneslsplw', crypt('iupf', gen_salt('bf')));
insert into User_Details values ('9635', 'zbknhkw', 'panlt', '7721122', 'irjcddsoz', crypt('yveg', gen_salt('bf')));
insert into Identty values (default, 'lrbbmqbh', '2020/02/02');
insert into Identty values (default, 'arzowkkyh', '2020/02/02');
insert into Identty values (default, 'dqscdxrjm', '2020/02/02');
insert into Identty values (default, 'frxsjybldb', '2020/02/02');
insert into Identty values (default, 'sarcbynec', '2020/02/02');
insert into Identty values (default, 'ggxx', '2020/02/02');
insert into Identty values (default, 'lorell', '2020/02/02');
insert into Identty values (default, 'papqfw', '2020/02/02');
insert into Identty values (default, 'opkmc', '2020/02/02');
insert into Identty values (default, 'hnwnku', '2020/02/02');
insert into Identty values (default, 'hsqmgbbuqc', '2020/02/02');
insert into Identty values (default, 'jiv', '2020/02/02');
insert into Identty values (default, 'mdkq', '2020/02/02');
insert into Identty values (default, 'xixmvtr', '2020/02/02');
insert into Identty values (default, 'ljp', '2020/02/02');
insert into Identty values (default, 'snfwzqfjm', '2020/02/02');
insert into Identty values (default, 'adr', '2020/02/02');
insert into Identty values (default, 'so', '2020/02/02');
insert into Identty values (default, 'bc', '2020/02/02');
insert into Identty values (default, 'vqhffbsaqx', '2020/02/02');
insert into Category values (default, 'wlrbb');
insert into Category values (default, 'qbhcdarz');
insert into Category values (default, 'wkkyhidd');
insert into Category values (default, 'scdx');
insert into Category values (default, 'jmowfrx');
insert into Category values (default, 'jybldbef');
insert into Category values (default, 'arcbynecdy');
insert into Category values (default, 'gx');
insert into Category values (default, 'pklorel');
insert into Category values (default, 'nmpap');
insert into Category values (default, 'fwkhop');
insert into Category values (default, 'mcoqhnwnku');
insert into Category values (default, 'whsqmgbb');
insert into Category values (default, 'qc');
insert into Category values (default, 'jjivswmdk');
insert into Category values (default, 'tbxixmvt');
insert into Category values (default, 'rbljptnsn');
insert into Category values (default, 'wzqfj');
insert into Category values (default, 'afadrr');
insert into Category values (default, 'so');
